server:
  port: 8002
  servlet:
    context-path:

#logging:
#  config: classpath:logback-spring.xml

spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    url: jdbc:mysql://47.113.147.111:3306/flowable_study?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      maxActive: 20
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      # 配置获取连接等待超时的时间
      maxWait: 60000
      minIdle: 1
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 关闭PS Cache
      poolPreparedStatements: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        #enabled: false 这里设为false直接禁用访问页面，默认为true，有登录页面
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        # allow: 127.0.0.1
        # IP黑名单 (存在共同时，deny优先于allow)
        # deny: 111.111.3.111
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        #druid登录页面账号密码
        # 登录名
        login-username: citydo
        # 登录密码
        login-password: Citydo@123


swagger:
  enable: true

#  mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true

## flowable.check-process-definitions：表示在项目启动的时候，去检查文件目录是否有对应的流程文件，默认值为 true 表示如果有流程文件就自动部署，false 表示不检查，那么也就不会自动部署
#flowable.process-definition-location-prefix：这个是流程文件的位置，默认就是 classpath*:/processes/，当然开发者也可以进行配置
#flowable.process-definition-location-suffixes：这个是流程文件的后缀，默认有两个，分别是 **.bpmn20.xml 和 **.bpmn，当然开发者也可以进行配置

  check-process-definitions: true
  process-definition-location-prefix: classpath*:/processes/
#  process-definition-location-suffixes:
#    - **.bpmn
#    - **.bpmn20.xml
  database-schema-update: true


logging:
  level:
    org:
      flowable: debug